name: flet_desktop_drop
description: Flet FletDesktopDrop control
repository: https://github.com/Wanna-Pizza/flet-desktop-drop/src/flutter/flet_desktop_drop
version: 0.1.0
homepage: https://github.com/Wanna-Pizza/flet-desktop-drop

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet:
    git:
      url: https://github.com/flet-dev/flet.git
      path: packages/flet
      ref: v1
  flutter:
    sdk: flutter
  desktop_drop: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
